### PR TITLE
add decision tags

### PR DESCRIPTION
**Pull request by melisabok**
I run this in live, please don't merge it. I want to do the same for the other NIPS workshop. 

Let me know if you any bugs.

### CODE REVIEW

**Comment by melisabok** [comment]
@zbialecki: I applied the same changes to the MLTIS webfield.

**Comment by melisabok** [comment]
Thanks! This is ready to merge.

**Comment by pmandler** [comment]
For the MLITS version, why not use NIPS.cc/2017/Workshop/MLITS/-/Paper.*/Acceptance_Decision? 

There is no need to include: 
 +import csv
 +import sys
 +sys.path.insert(0, "./..")
 +import config

**Comment by melisabok** [comment]
I'm sorry, I missed them, probably because they are not public. By the way those notes have the values: accept or reject. It is better to have in the tags options like: oral, poster or reject

**Comment by melisabok** [comment]
is this ready to merge?

**Pull request merged**
