### PR TITLE
Fix/UAI homepage tabs fixes

### PR DESCRIPTION
**Pull request by zbialecki**
This PR is not quite ready to be merged yet, still missing is the My Tasks tab for the homepage

### CODE REVIEW

**Comment by zbialecki** [comment]
Should be ready to go now, but we can wait to merge until it's tested on dev.

**Comment by melisabok** [comment]
sounds good to me.

**Comment by mspector** [comment]
I think this is ready to be merged. any objections?

@zbialecki @melisabok

**Comment by zbialecki** [comment]
Nope, I think it's ready.

**Pull request merged**
