### PR TITLE
Add AC's to output

### PR DESCRIPTION
**Pull request by pmandler**

### CODE REVIEW

**Comment by melisabok** [comment]
sounds good to me

**Comment by mspector** [comment]
looks good! one suggestion:

instead of formatting it like "Paper Number, AC, Reviewers" in order like that, could you do something like:

[Paper_Number, Reviewers, "(Area Chair: " + AC + ")"]

Does that make sense? I think it will make the output easier to read

**Comment by melisabok** [comment]
the problem of that is that reviewers list is not fixed.

**Comment by pmandler** [comment]
At first I had it paper number  AC: name, Reviewers: names, but I thought it would be unwieldy if they wanted to copy it into a spreadsheet and work with it from there.  

Pam

**Comment by mspector** [comment]
ok, fair enough

**Pull request merged**
