### PR TITLE
get assgigned papers from the anonreviewer groups

### PR DESCRIPTION
**Pull request by melisabok**
it is deployed in dev

### CODE REVIEW

**Comment by melisabok** [comment]
Thanks!!!

**Comment by zbialecki** [comment]
Everything seems to be working as expected. I'm a little confused by one thing though - why there are 2 papers listed under the My Tasks tab, but then My Assigned Papers has 5 papers (including the 2 from My Tasks)?

**Comment by melisabok** [comment]
My Tasks shows the 2 papers that the review is missing. If you go to 'My Comments and Reviews' you can see 3 reviews done. So 2 missing reviews + 3 reviews done = 5 assigned papers.

**Comment by melisabok** [comment]
My Tasks could be renamed to My Pending Tasks. That's confusing I think

**Comment by zbialecki** [comment]
Ah I see, thanks! I think I was also confused because Red Paper had a comment, but not an official review. I agree that My Tasks could maybe be named better.

**Comment by mspector** [comment]
One more question before we merge: am I supposed to be seeing the author IDs in the my assigned papers tab?

**Comment by mspector** [comment]
I've tested this and deployed it to the live site. I'm on a spotty internet connection but when I can I'll send out the reviewer emails that Tara asked for

**Pull request merged**
