### PR TITLE
ignore hard constraints while computing final score

### PR DESCRIPTION
**Pull request by mspector**

### CODE REVIEW

**Comment by melisabok** [comment]
Thanks @mspector ! Thanks for fixing the typos 👍

**Comment by mspector** [comment]
@melisabok sorry for the delay, the fix has been applied to the reviewers script now

**Comment by melisabok** [comment]
Ok, I will merge it. But we must to read the scores from the matching result

**Comment by melisabok** [comment]
and we need to replicate the same changes in ECCV. I don't agree doing this.

**Comment by mspector** [comment]
@melisabok are you worried that we're replicating too much code? I can generalize this so that we use the same script for all four cases (UAI ACs and Reviewers, ECCV ACs and Reviewers)

**Comment by mspector** [comment]
FYI to anyone else following this: @melisabok and I discussed this, and I'm going to generalize these scripts to avoid repetition. I'm keeping open this PR for now, so that we can reference it. I will close it when I have a new PR ready.

**Pull request closed without merging**
