### PR TITLE
Iclr2018/workshop submission from conference

### PR DESCRIPTION
**Pull request by mspector**

### CODE REVIEW

**Comment by melisabok** [comment]
It is property that we send to mkNotePanel (showOriginal: true I guess).

Check last year webfield:

https://openreview.net/group?id=ICLR.cc/2017/workshop

**Comment by melisabok** [comment]
Add this setting: withOriginalLink: true. 

here:

```
var paperDisplayOptions = {
  pdfLink: true,
  replyCount: true,
  showContents: true
};
```

**Comment by mspector** [comment]
I haven't been able to make this work. When you have a moment could we go over it?

**Comment by mspector** [comment]
@melisabok can this be merged?

**Pull request merged**
